apiVersion: v1
kind: Pod
metadata:
  name: xcache-client-pod
  labels:
    app: xcache-client
spec:
  containers:
  - name: xcache-container
    image: slateci/xcache:latest
    command: ["sleep"]
    args: ["36500000"]
  restartPolicy: Never