kind: Service
apiVersion: v1
metadata:
  name: xcache-service
spec:
  type: NodePort
  selector:
    app: xcache
  ports:
  - protocol: TCP
    name: xrootd
    port: 1094
    targetPort: 1094
    nodePort: 31094
---
apiVersion: v1
kind: Pod
metadata:
  name: xcache-pod
  labels:
    app: xcache
spec:

  volumes:
  - name: x509-data
    emptyDir: {}
  - name: x509-certs-volume
    secret:
      secretName: xcache-cert-secret
  #   defaultMode: 256 # default is 0644; 256 is 0400

  containers:
  - name: xcache-container
    image: slateci/xcache:latest
    env:
    - name: XC_SPACE_HIGH_WM
      value: "0.95"
    - name: XC_SPACE_LOW_WM
      value: "0.80"
    - name: XC_PORT
      value: "1094"
    - name: XC_RAMSIZE
      value: "1g"
    - name: XC_BLOCKSIZE
      value: "1M"
    - name: XC_PREFETCH
      value: "0"
    volumeMounts:
    - name: x509-data
      mountPath: "/etc/grid-security/"
      readOnly: true
    - name: x509-certs-volume
      mountPath: "/root/.globus"
    ports:
      - containerPort: 1094

  - name: x509-container
    image: slateci/xcache:latest
    command: ["/run_x509_updater.sh"]
    volumeMounts:
    - name: x509-data
      mountPath: "/etc/grid-security/"
      readOnly: false
    - name: x509-certs-volume
      mountPath: "/root/.globus"

  - name: reporter-container
    image: slateci/xcache:latest
    command: ["/run_cache_reporter.sh"]

  restartPolicy: Never