apiVersion: v1
kind: Pod
metadata:
  name: xcache-pod
spec:
  containers:
  - name: xcache-container
    image: slateci/xcache:latest
    command: ["sleep"]
    args: ["36500000"]
    env:
      - name: SPACE_HIGH_WM
        value: 0.95
      - name: SPACE_HIGH_WM
        value: 0.80
      - name: PORT
        value: 1094
  #   volumeMounts:
  #   - name: keytab-volume
  #     mountPath: "/tmp/keytab"
  #     readOnly: true
  # volumes:
  # - name: keytab-volume
  #   secret:
  #     secretName: analytcssvc-keytab
  restartPolicy: Never