apiVersion: v1
kind: Pod
metadata:
  name: xcache-client-pod
  labels:
    app: xcache-client
spec:
  containers:
  - name: xcache-container
    image: slateci/xcache:latest
    command: ["stress_test.sh"]
    args: ["root://es-docker.mwt2.org:1094"]
    # env:
    # - name: XC_PREFETCH
    #   value: "0"
  #   volumeMounts:
  #   - name: keytab-volume
  #     mountPath: "/tmp/keytab"
  #     readOnly: true
  # volumes:
  # - name: keytab-volume
  #   secret:
  #     secretName: analytcssvc-keytab
  restartPolicy: Never