kind: Pod
apiVersion: v1
metadata:
  name: xcache-pod
  labels:
    app: xcache
spec:

  nodeSelector:
    xcache-capable: "true"

  volumes:
  - name: x509-data
    emptyDir: {}
  - name: x509-certs-volume
    secret:
      secretName: xcache-cert-secret
      items:
      - key: userkey
        path: userkey.pem
        mode: 256 
      - key: usercert
        path: usercert.pem
  - name: xcache-data
    hostPath:
      path: /scratch

  containers:
  - name: xcache-container
    image: slateci/xcache:latest
    env:
    - name: XC_SPACE_HIGH_WM
      value: "0.95"
    - name: XC_SPACE_LOW_WM
      value: "0.80"
    - name: XC_PORT
      value: "1094"
    - name: XC_RAMSIZE
      value: "1g"
    - name: XC_BLOCKSIZE
      value: "1M"
    - name: XC_PREFETCH
      value: "0"
    volumeMounts:
    - name: x509-data
      mountPath: "/etc/grid-security/"
      readOnly: false
    - name: x509-certs-volume
      mountPath: "/etc/grid-certs/"
      readOnly: true
    - name: xcache-data
      mountPath: "/cache"
      readOnly: false

    ports:
      - containerPort: 1094

  - name: x509-container
    image: slateci/xcache:latest
    command: ["/run_x509_updater.sh"]
    volumeMounts:
    - name: x509-data
      mountPath: "/etc/grid-security/"
      readOnly: false
    - name: x509-certs-volume
      mountPath: "/etc/grid-certs/"
      readOnly: true

  - name: reporter-container
    image: slateci/xcache:latest
    command: ["/run_cache_reporter.sh"]
    env:
    - name: XC_SITE
      value: "MWT2"
    volumeMounts:
    - name: xcache-data
      mountPath: "/cache"
      readOnly: true
      
  restartPolicy: Never