kind: Service
apiVersion: v1
metadata:
  name: xcache-service
spec:
  type: NodePort
  selector:
    app: xcache
  ports:
  - protocol: TCP
    name: xrootd
    port: 1094
    targetPort: 1094
    nodePort: 31094
---
apiVersion: v1
kind: Pod
metadata:
  name: xcache-pod
  labels:
    app: xcache
spec:
  containers:
  - name: xcache-container
    image: slateci/xcache:latest
    env:
    - name: XC_SPACE_HIGH_WM
      value: "0.95"
    - name: XC_SPACE_LOW_WM
      value: "0.80"
    - name: XC_PORT
      value: "1094"
    - name: XC_RAMSIZE
      value: "1g"
    - name: XC_BLOCKSIZE
      value: "1M"
    - name: XC_PREFETCH
      value: "0"
    volumeMounts:
    - name: xcache-proxy-volume
      mountPath: "/var/run/"
      # readOnly: true
    - name: xcache-cert-volume
      mountPath: "/etc/grid-security/certificates/"
      # readOnly: true
    - name: xcache-vomsdir-volume
      mountPath: "/etc/grid-security/vomsdir/"
      # readOnly: true
  volumes:
  - name: xcache-proxy-volume
    secret:
      secretName: xcache-proxy-secret
      defaultMode: 256 # default is 0644; 256 is 0400
  - name: xcache-cert-volume
    secret:
      secretName: xcache-cert-secret
  - name: xcache-vomsdir-volume
    secret:
      secretName: xcache-vomsdir-secret
  restartPolicy: Never