kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "osg-frontier-squid.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.XCacheConfig.CacheSize }}Gi
  storageClassName: nfs-provisioner